### ISSUE TITLE
Decimal in database

### ISSUE THREAD

**Issue by kasp470f** [kasp470f/1yearProject#40]

**Comment by mathex83** [comment]
Ofte er alle felter indlejret i dobbelt anførselstegn, hvilket også er tilfældet for dette projekt, dette bruges for dermed f.eks. at sikre komma kan bruges som decimalpunkt og i tekst.

**Comment by mathex83** [comment]
Fixed by setting amount in db as a fixed decimal(18,3) instead of just decimal which apparently autosets it to decimal(30,0)
