### ISSUE TITLE
Rapporten

### ISSUE THREAD

**Issue by kasp470f** [kasp470f/1yearProject#8]
Selve rapport skrivningen

**Comment by mathex83** [comment]
Status 25/5:

<details>

- [x] Forside med titel
- [ ] Forord
- [x] Indholdsfortegnelse (er sat op og ska bare opdateres når rapport er færdig)
- [x] Problemstilling
  formodes færdig...
- [x] Problemformulering
  formodes færdig

Inception
- [ ] Virksomhedsanalyse
- [ ] Problemanalyse

Elaboration
- [ ] Low- og High Fidelity Prototyper
- [ ] Domænemodel færdig
- [ ] Datamodel ERD færdig
- [ ] Mappingskema
- [ ] SQL, DML og DDL
- [ ] Sekvensdiagrammer
- [ ] Strukturel Designmodel (Klassediagrammet)

Iteration 1
- [ ] Analyse (definitionen af fully dressed use case)
- [ ] Design
- [ ] Implementering
- [ ] Test
- [ ] Konklusion

Iteration 2
- [ ] Analyse
- [ ] Design
- [ ] Implementering
- [ ] Test
- [ ] Konklusion

Construction
- [x] Iteration Sql...
- [ ] Iteration C# og XAML

Transition
- [ ] Iteraion?


		
- [ ] Tilgangsvinkler

 - Baggrund, teori, metode, analyse, herunder beskrivelse af og begrundelse for valg af eventuel empiri, til besvarelse af problemformuleringen
 - Systemudviklingsartefakter der indgår i systemudviklingsprocessen, herunder argumenter for valget af systemudviklingsartefakter.

- [ ] Konklusion

- [ ] Perspektivering
  er i gang

- [x] Litteraturliste (inkl. alle kilder, der er lavet henvisninger til i projektet)
  opdateres løbende ved nye ting men er gjort klar til brug og begyndt på

- [ ] Bilag (inkluder kun bilag, som er centrale for rapporten)
  vi har ingen endnu

</details>

**Comment by mathex83** [comment]
Status 27/5 (forkortet):

<details>


- [ ] Forord
- [x] Indholdsfortegnelse (er sat op og ska bare opdateres når rapport er færdig)

Construction

- [ ] Strukturel Designmodel (Klassediagrammet)
  Kan først færdiggøres når alle klasser er der
- [ ] Forklaring til klassemodellen??
- [ ] Iteration C# og XAML

Transition
- [ ] Test
  i gang
- [ ] Konklusion

Tilgangsvinkler
- [ ] Beskrive tilgangsvinkler
 - Baggrund, teori, metode, analyse, herunder beskrivelse af og begrundelse for valg af eventuel empiri, til besvarelse af problemformuleringen
 - Systemudviklingsartefakter der indgår i systemudviklingsprocessen, herunder argumenter for valget af systemudviklingsartefakter.

- [ ] Konklusion

- [ ] Perspektivering
  er i gang

- [x] Litteraturliste (inkl. alle kilder, der er lavet henvisninger til i projektet)
  opdateres løbende ved nye ting men er gjort klar til brug og begyndt på

- [x] Bilag (inkluder kun bilag, som er centrale for rapporten)
  vi har ingen endnu

</details>

**Comment by mathex83** [comment]
Status 04/06 (forkortet):

<details>


- [ ] Forord
- [ ] Konklusion

- [ ] Perspektivering
  er i gang

</details>
