### ISSUE TITLE
StatisticsPage

### ISSUE THREAD

**Issue by mathex83** [kasp470f/1yearProject#93]
- [x] Statistik-ikonet har farver som det eneste…

- [x] Graferne er blå og rundt om graf-området er der blåt... Vi ønskede få farver så at introducere blå her virker kikset…

- [x] Der står ved X “Months” (engelsk) Y “Amount” (Engelsk)... Det passer ik med at holde den på dansk, specielt ik når de enkelte mdr. står på dansk…
- [ ] Der står i projektoplægget at vi skal vise en sammenligning af mængder på tværs af affaldstyper… Kan vi tilpasse app til det?

**Comment by kasp470f** [comment]
> Statistik-ikonet har farver som det eneste…
Kan jeg ændre

**Comment by kasp470f** [comment]
![image](https://user-images.githubusercontent.com/55143058/120452536-8c372d80-c392-11eb-90b0-29a8baf38d87.png)

**Comment by kasp470f** [comment]
> Der står i projektoplægget at vi skal vise en sammenligning af mængder på tværs af affaldstyper… Kan vi tilpasse app til det?
Det har vi allerede. Det er med combobox, hvis vi har for meget på siden så vil det være hårdt på CPU'en

**Comment by mathex83** [comment]
Hellere dansk på det hele hvis muligt
